
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import OTCEscrowContractContractArtifactJson from '../target/otc_escrow-OTCEscrowContract.json' with { type: 'json' };
export const OTCEscrowContractContractArtifact = loadContractArtifact(OTCEscrowContractContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract OTCEscrowContract;
 */
export class OTCEscrowContractContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, OTCEscrowContractContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, OTCEscrowContractContract.artifact, wallet) as Promise<OTCEscrowContractContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, offer_token_address: AztecAddressLike, offer_token_amount: (bigint | number), ask_token_address: AztecAddressLike, ask_token_amount: (bigint | number)) {
    return new DeployMethod<OTCEscrowContractContract>(PublicKeys.default(), wallet, OTCEscrowContractContractArtifact, OTCEscrowContractContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, offer_token_address: AztecAddressLike, offer_token_amount: (bigint | number), ask_token_address: AztecAddressLike, ask_token_amount: (bigint | number)) {
    return new DeployMethod<OTCEscrowContractContract>(publicKeys, wallet, OTCEscrowContractContractArtifact, OTCEscrowContractContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof OTCEscrowContractContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<OTCEscrowContractContract['methods'][M]>
  ) {
    return new DeployMethod<OTCEscrowContractContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      OTCEscrowContractContractArtifact,
      OTCEscrowContractContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return OTCEscrowContractContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(OTCEscrowContractContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'definition' | 'maker_secret'> {
      return {
        definition: {
      slot: new Fr(1n),
    },
maker_secret: {
      slot: new Fr(2n),
    }
      } as ContractStorageLayout<'definition' | 'maker_secret'>;
    }
    

  public static get notes(): ContractNotes<'UintNote' | 'DefinitionNote' | 'MakerNote'> {
    return {
      UintNote: {
          id: new NoteSelector(0),
        },
DefinitionNote: {
          id: new NoteSelector(1),
        },
MakerNote: {
          id: new NoteSelector(2),
        }
    } as ContractNotes<'UintNote' | 'DefinitionNote' | 'MakerNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(offer_token_address: struct, offer_token_amount: integer, ask_token_address: struct, ask_token_amount: integer) */
    constructor: ((offer_token_address: AztecAddressLike, offer_token_amount: (bigint | number), ask_token_address: AztecAddressLike, ask_token_amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deposit_tokens(maker_secret: field, _nonce: field) */
    deposit_tokens: ((maker_secret: FieldLike, _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** fill_order(_nonce: field) */
    fill_order: ((_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** finalize_order(maker_secret: field) */
    finalize_order: ((maker_secret: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_definition() */
    get_definition: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_maker_secret() */
    get_maker_secret: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
